// <auto-generated />
namespace Sale.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class crear_tabla_productos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crear_tabla_productos));
        
        string IMigrationMetadata.Id
        {
            get { return "202002061414387_crear_tabla_productos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
